'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddPayment

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''SearchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SearchInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OrdersListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrdersListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''OrdersDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrdersDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''OrderInfoTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderInfoTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''BuyersCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyersCell As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''PropertyOwnerCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCell As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''PropertyOwnerAddressCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddressCell As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TotalAmountOwedCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalAmountOwedCell As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TotalAmountPaidCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalAmountPaidCell As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''PaymentHistoryGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentHistoryGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''PaymentHistoryDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentHistoryDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PaymentInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PaymentDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PaymentSourceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentSourceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PaymentSourceDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentSourceDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PaymentCheckPaypalNumberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentCheckPaypalNumberInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PaymentPaypalTransactionInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentPaypalTransactionInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NewPaymentButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPaymentButton As Global.System.Web.UI.WebControls.Button
End Class
