'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AddNewUserButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddNewUserButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ViewUsersButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewUsersButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OccasionMaintenanceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OccasionMaintenanceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PropertyTraitMaintenanceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyTraitMaintenanceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''OrderSourceMaintenanceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSourceMaintenanceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DiscountMaintenanceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountMaintenanceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PaymentSourceMaintenanceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentSourceMaintenanceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MarkAllRoutesUnchangedButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarkAllRoutesUnchangedButton As Global.System.Web.UI.WebControls.Button
End Class
