'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin

    '''<summary>
    '''TraitDecriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TraitDecriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TraitDecription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TraitDecription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TraitDecriptionEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TraitDecriptionEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TraitDecriptionFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TraitDecriptionFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator
End Class
