'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class New_Order

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''OrderDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderBasePriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderBasePriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderBasePriceInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderBasePriceInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderDiscountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderDiscountDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscountDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderDiscountSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscountSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''OrderSubscriptionYearLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSubscriptionYearLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderSubscriptionYearInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSubscriptionYearInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderFirstOccasionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderFirstOccasionDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderFirstOccasionSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BuyerFormatTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFormatTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''BuyerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BuyerSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BuyerFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerFirstNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerLastNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerAddressInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerCityInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerStateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BuyerZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerZipCodeInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerEmailInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerPhoneInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerRotaryMemberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRotaryMemberInput As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BuyerAddButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BuyerRemoveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRemoveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BuyerListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''PropertyOwnerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PropertyOwnerSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PropertyOwnerFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerFirstNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFirstNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerLastNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLastNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerAddressInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddressInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerCityInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCityInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerStateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerStateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PropertyOwnerZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerZipCodeInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerZipCodeInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerEmailInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerEmailInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerPhoneInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerPhoneInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerRotaryMemberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerRotaryMemberInput As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
End Class
