'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class New_Order

    '''<summary>
    '''BuyerUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''BuyerLayoutTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLayoutTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''BuyerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BuyerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BuyerFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerFirstNameEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuyerFirstNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerLastNameEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuyerLastNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerAddressFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerCityFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerStateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerZipCodeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerEmailFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerPhoneFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerRotaryMember control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRotaryMember As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BuyerAddButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BuyerRemoveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRemoveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BuyerListView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerListView As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
End Class
