'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class New_Order

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''OrderDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''OrderCostLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderCostLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderCostInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderCostInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderCostFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderCostFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OrderAmountPaidLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderAmountPaidLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderAmountPaidInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderAmountPaidInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderAmountPaidFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderAmountPaidFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OrderPaymentSourceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentSourceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderPaymentSourceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentSourceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderPaymentSourceDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentSourceDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''OrderPaymentMemoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentMemoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderPaymentMemoInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentMemoInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderDiscountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderDiscountDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscountDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderDiscountSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscountSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''OrderSourceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSourceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderSourceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSourceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderSourceSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSourceSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''OrderSubscriptionYearLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSubscriptionYearLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderSubscriptionYearInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSubscriptionYearInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubscriptionYearFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriptionYearFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OrderFirstOccasionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderFirstOccasionDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderFirstOccasionSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BuyerFormatTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFormatTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''BuyerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BuyerSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BuyerFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerFirstNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerFirstNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerLastNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerLastNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerAddressInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerAddressFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerCityInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerCityFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerStateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BuyerZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerZipCodeInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerZipCodeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerEmailInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerEmailFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerPhoneInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerPhoneFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerRotaryMemberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRotaryMemberInput As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BuyerAddButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BuyerRemoveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRemoveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BuyerListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''PropertyOwnerFormatTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFormatTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''PropertyOwnerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PropertyOwnerSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PropertyOwnerFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerFirstNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFirstNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerFirstNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFirstNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerLastNameInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLastNameInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerLastNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLastNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerAddressInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddressInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerAddressFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddressFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerCityInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCityInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerCityFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCityFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerStateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerStateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PropertyOwnerZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerZipCodeInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerZipCodeInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerZipCodeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerZipCodeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerEmailInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerEmailInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerEmailFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerEmailFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerPhoneInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerPhoneInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyOwnerPhoneFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerPhoneFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerRotaryMemberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerRotaryMemberInput As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PropertyTraitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyTraitsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyTraits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyTraits As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''Traits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Traits As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PropertyOwnerAddButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PropertyOwnerRemoveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerRemoveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PropertyOwnerListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''SleeveFormatTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveFormatTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''SleevePropertyDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleevePropertyDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SleeveLocationDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLocationDescriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveLocationDescriptionInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLocationDescriptionInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SleeveLatitudeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLatitudeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveLatitudeInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLatitudeInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SleeveLatitudeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLatitudeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''SleeveLongitudeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLongitudeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveLongitudeInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLongitudeInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SleeveLongitudeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLongitudeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OupsNotifiedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsNotifiedDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OupsNotifiedDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsNotifiedDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OupsNotifiedDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsNotifiedDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''OupsTicketNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsTicketNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OupsTicketNumberInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsTicketNumberInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OupsTicketNumberFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsTicketNumberFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OupsCheckedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsCheckedDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OupsCheckedDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsCheckedDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OupsCheckedDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsCheckedDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''SleeveInstallDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveInstallDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveInstallDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveInstallDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SleeveInstallDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveInstallDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''SleeveChangeDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveChangeDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveChangeDateInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveChangeDateInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SleeveChangeDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveChangeDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''SleevePublicCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleevePublicCheckbox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SleeveDeliverCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveDeliverCheckbox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SleeveAddButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveAddButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SleeveRemoveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveRemoveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SleeveListBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveListBox As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabName As Global.System.Web.UI.WebControls.HiddenField
End Class
