'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class New_Entry

    '''<summary>
    '''BuyerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BuyerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BuyerFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerFirstNameEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuyerFirstNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerFirstNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerLastNameEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BuyerLastNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerLastNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerAddressFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerAddressFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerCityFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerCityFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerStateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerStateFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerZipCodeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerZipCodeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerEmailFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerEmailFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BuyerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BuyerPhoneFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerPhoneFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BuyerRotaryMember control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BuyerRotaryMember As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''OrderDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderDateEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OrderDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''OrderSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderSourceDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSourceDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderSourceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSourceList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SubscriptionYearLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriptionYearLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderSubscriptionYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderSubscriptionYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubscriptionYearEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriptionYearEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SubscriptionYearFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriptionYearFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OrderTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ConfirmationDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmationDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderConfirmationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderConfirmationDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ConfirmationDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmationDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''ExpireDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpireDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderExpireDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ExpireDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpireDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''PropertyOwnerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PropertyOwnerList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PropertyFirstNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyFirstNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyFirstNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyFirstNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyLastNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyLastNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyLastNameFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyLastNameFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyAddressEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyAddressEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PropertyAddressFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyAddressFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyCityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyCityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyCityEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyCityEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PropertyCityFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyCityFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ProprtyStateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProprtyStateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyStateEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyStateEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PropertyStateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyStateFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyZipCodeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyZipCodeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyZipCodeEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyZipCodeEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PropertyZipCodeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyZipCodeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyEmailLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyEmailLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyEmailFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyEmailFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyOwnerPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PropertyPhoneFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyPhoneFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PropertyOwnerRotaryMember control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyOwnerRotaryMember As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''PropertyTraitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyTraitsLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PropertyTraits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyTraits As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''Traits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Traits As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''LocationDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationDescriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveLocationDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLocationDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SleevePhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleevePhoto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ImageValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''AddAnotherImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddAnotherImage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LatitudeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LatitudeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLatitude As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LatitudeEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LatitudeEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LatitudeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LatitudeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''LongitudeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LongitudeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveLongitude As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LongitudeEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LongitudeEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LongitudeFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LongitudeFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OUPSNotifiedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSNotifiedDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OupsNotifiedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsNotifiedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OUPSNotifiedDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSNotifiedDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''OUPSTicketNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSTicketNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OupsTicketNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsTicketNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OUPSTicketNumberEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSTicketNumberEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''OUPSTicketNumberFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSTicketNumberFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OUPSCheckedDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSCheckedDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OupsCheckedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OupsCheckedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OUPSCheckedDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OUPSCheckedDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''InstallDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstallDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveInstallDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveInstallDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''InstallDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstallDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''ChangeDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangeDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SleeveChangeDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveChangeDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChangeDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangeDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''SleevePublic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleevePublic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''SleeveDeliver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveDeliver As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''BasePriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BasePriceLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderBasePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderBasePrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BasePriceEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BasePriceEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BasePriceFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BasePriceFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''OrderPaymentMethodLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentMethodLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderPaymentMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentMethod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OrderPaymentSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderPaymentSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DiscountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDiscount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DiscountName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''AmountPaidLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaidLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PaymentAmountPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentAmountPaid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AmountPaidEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaidEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AmountPaidFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaidFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PaymentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentDateLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PaymentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PaymentDateEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentDateEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PaymentDateFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentDateFormatValidator As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''OrderFirstOccasionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderFirstOccasion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderFirstOccasion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''OccasionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OccasionName As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button
End Class
