'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin

    '''<summary>
    '''DiscountDescriptionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountDescriptionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DiscountDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DiscountDescriptionEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountDescriptionEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DiscountDescriptionFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountDescriptionFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''DiscountAmountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountAmountLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DiscountAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DiscountAmountEnteredValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountAmountEnteredValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DiscountAmountFormatValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountAmountFormatValidator As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''DiscountActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountActive As Global.System.Web.UI.WebControls.CheckBox
End Class
