'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reports
    
    '''<summary>
    '''CustomerReportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerReportButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PaymentReportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaymentReportButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''FinanceReportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FinanceReportButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SubcriberCommunicationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubcriberCommunicationButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NonSubscriberCommunicationButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NonSubscriberCommunicationButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RouteReportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RouteReportButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''SleeveReportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SleeveReportButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GPSDataButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GPSDataButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''EmailListDataButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailListDataButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''MailingListButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MailingListButton As Global.System.Web.UI.WebControls.Button
End Class
